meta_product_name: "A day in a movie"
meta_title: "A day in a movie - Rent any item from your favorite movie"
meta_description: "Have you ever dream to live in your favorite character's shoes during one day ? It's now possible with \"A day in a movie\", the place where you can rent any item from your favorite movie !"
meta_image: "cover.png" # should exist in `app/assets/images/`
