# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
Movie.destroy_all
Prop.destroy_all
User.destroy_all
Booking.destroy_all

puts 'users'
user1 = User.create!(email: "flo@go.com", password: "azerty")
user2 = User.create!(email: "lisa@go.com", password: "azerty")
user3 = User.create!(email: "steven@go.com", password: "azerty")

puts 'movies'
star_wars = Movie.create(name: "Star Wars")
got = Movie.create(name: "Game of thrones")
shinning = Movie.create(name: "The Shinning")
harry_potter = Movie.create(name: "Harry Potter")
retour_futur = Movie.create(name: "Retour vers le futur")
batman = Movie.create(name: "Batman")
lord_rings = Movie.create(name: "Lord of the rings")
kill_bill = Movie.create(name: "Kill Bill")
iron_man = Movie.create(name: "Iron Man")
matrix = Movie.create(name: "Matrix")
terminator = Movie.create(name: "Terminator")
indiana_jones = Movie.create(name: "Indiana Jones")
avengers = Movie.create(name: "Avengers")
avatar = Movie.create(name: "Avatar")
friends = Movie.create(name: "Friends")
big_bang_theory = Movie.create(name: "Big bang theory")
pirates_des_caraibes = Movie.create(name: "Pirates des caraïbes")
peaky_blinders = Movie.create(name: "Peaky blinders")
walking_dead = Movie.create(name: "Walking dead")
casa_de_papel = Movie.create(name: "Casa de papel")
titanic = Movie.create(name: "Titanic")
cinquieme_element = Movie.create(name: "Le Cinquieme élément")
jurassik_park = Movie.create(name: "Jurassik Park")
james_bond = Movie.create(name: "James Bond")

puts 'objects'
sabre_laser = Prop.create!(name: "Sabre Laser", movie: star_wars, user: user1)
dark_vador = Prop.create(name: "Dark Vador costume", movie: star_wars, user: user1)
helmet_stormtrooper = Prop.create(name: "Stormtrooper Helmet", movie: star_wars, user: user1)
yoda = Prop.create(name: "Yoda", movie: star_wars, user: user1)
r2 = Prop.create(name: "R2 - D2", movie: star_wars, user: user1)
throne = Prop.create(name: "Trone de fer", movie: got, user: user1)
ring_got = Prop.create(name: "Daenerys ring", movie: got, user: user1)
manteau = Prop.create(name: "Manteau de John Snow", movie: got, user: user1)
white_walker = Prop.create(name: "White walker", movie: white_walker, user: user1)
machine_ecrire = Prop.create(name: "Machine à écrire", movie: shinning, user: user1)
baguette_hp = Prop.create(name: "Baguette d'Harry Potter", movie: harry_potter, user: user1)
balai_hp = Prop.create(name: "Balai d'Harry Potter", movie: harry_potter, user: user1)
vif_or_hp = Prop.create(name: "Vif d'or d'Harry Potter", movie: harry_potter, user: user1)
chapeau_hp = Prop.create(name: "Chapeau d'Harry Potter", movie: harry_potter, user: user2)
lunettes_hp = Prop.create(name: "Lunnettes d'Harry Potter", movie: harry_potter, user: user2)
livre_hp = Prop.create(name: "Livre magique d'Harry Potter", movie: harry_potter, user: user2)
skate_retour_futur = Prop.create(name: "Marty McFly's overboard", movie: retour_futur, user: user2)
guitar_retour_futur = Prop.create(name: "Guitare de Marty McFly", movie: retour_futur, user: user2)
dolorean = Prop.create(name: "Dolorean", movie: retour_futur, user: user2)
un_jb = Prop.create(name: "Gun de James Bond", movie: james_bond, user: user2)
voiture = Prop.create(name: "Voiture de James Bond", movie: james_bond, user: user2)
bague_intelligente = Prop.create(name: "Bague intelligente", movie: james_bond, user: user2)
marteau = Prop.create(name: "Marteau de Thor", movie: avengers, user: user2)
bouclier = Prop.create(name: "Bouclier de Captain America", movie: avengers, user: user2)
jeep = Prop.create(name: "Jeep", movie: jurassik_park, user: user2)
costume_ce = Prop.create(name: "Costume Leeloo", movie: cinquieme_element, user: user2)
arc = Prop.create(name: "Arc d'Avatar", movie: avatar, user: user2)
bijou = Prop.create(name: "Bijou d'Avatar", movie: avatar, user: user2)
canape = Prop.create(name: "Canapé", movie: friends, user: user2)
tshirt_sheldon = Prop.create(name: "T-shirt de Sheldon", movie: big_bang_theory, user: user2)
waitress_uniform = Prop.create(name: "Waitress uniform", movie: big_bang_theory, user: user2)
sheldon_spot = Prop.create(name: "Spot de Sheldon", movie: big_bang_theory, user: user2)
jack_sparrow_costume = Prop.create(name: "Costume de Jack Sparrow", movie: pirates_des_caraibes, user: user2)
sabre= Prop.create(name: "Sabre de Jack Sparrow", movie: pirates_des_caraibes, user: user2)
radeau = Prop.create(name: "Radeau", movie: titanic, user: user2)
costume_pb = Prop.create(name: "Costume de Thomas Shelby", movie: peaky_blinders, user: user2)
zombie = Prop.create(name: "Zombie", movie: walking_dead, user: user2)
mask_combi = Prop.create(name: "Masque et combinaison", movie: casa_de_papel, user: user2)
manteau_matrix = Prop.create(name: "Manteau de Neo", movie: matrix, user: user2)
sunglasses_matrix = Prop.create(name: "Lunettes noires de Neo", movie: matrix, user: user2)
batmobile = Prop.create(name: 'BatMobile', movie: batman, user: user2)
joker_cards = Prop.create(name: 'Cartes du Joker', movie: batman, user: user2)
batman_cape = Prop.create(name: 'Cape de Batman', movie: batman, user: user2)
batmoto = Prop.create(name: 'BatMoto', movie: batman, user: user2)
bane_mask = Prop.create(name: 'Masque de Bane', movie: batman, user: user2)
ring_lord = Prop.create(name: 'L\'anneau Unique', movie: lord_rings, user: user2)
gandalf_baton = Prop.create(name: 'Le bâton magique de Gandalf', movie: lord_rings, user: user2)
legolas_arc = Prop.create(name: 'L\'arc de Légolas', movie: lord_rings, user: user2)
aragon_sword = Prop.create(name: 'L\'épée reforgée d\'Aragorn', movie: lord_rings, user: user2)
ring_lord = Prop.create(name: 'L\'anneau Unique', movie: lord_rings, user: user2)
gimmli_hache = Prop.create(name: 'La hâche de Gimli', movie: lord_rings, user: user2)
combi_killbill = Prop.create(name: 'Combinaison de Beatrix Kiddo', movie: kill_bill, user: user3)
sabre_killbill = Prop.create(name: 'Katana de Beatrix Kiddo', movie: kill_bill, user: user3)
cercueil_killbill = Prop.create(name: 'Cercueil de Beatrix Kiddo', movie: kill_bill, user: user3)
armure_ironman = Prop.create(name: 'Armure d\'Iron-Man', movie: iron_man, user: user3)
car_ironman = Prop.create(name: 'L\'Audi eTron GT de Tony Stark', movie: iron_man, user: user3)
glasses_terminator = Prop.create(name: 'Lunettes de Terminator', movie: terminator, user: user3)
gun_terminator = Prop.create(name: 'Winchester de Terminator', movie: terminator, user: user3)
arm_terminator = Prop.create(name: 'Bras robotisée de Terminator', movie: terminator, user: user3)
chapeau_indiana = Prop.create(name: 'Chapeau d\'Indiana Jones', movie: indiana_jones, user: user3)
lasso_indiana = Prop.create(name: 'Lasso d\'Indiana Jones', movie: indiana_jones, user: user3)
skull_indiana = Prop.create(name: 'Crâne de Cristal', movie: indiana_jones, user: user3)
moto_indiana = Prop.create(name: 'Moto d\'Indiana Jones', movie: indiana_jones, user: user3)
